### ISSUE TITLE
overlay

### ISSUE THREAD

**Issue by ebgoldstein** [dbuscombe-usgs/dash_doodler#20]
this does not warrant a PR. But on the gen_images* code currently puts all png files into the overlay folder.. 
https://github.com/dbuscombe-usgs/dash_doodler/blob/2f57f9f673b3f23540934614cbbe49103d624671/utils/gen_images_and_labels_4_zoo.py#L234-L236

this should be corrected:
```
ovfiles = glob(direc+'/*_overlay.png')
```

**Comment by ddbuscombe** [comment]
great. now fixed with last commit
