### ISSUE TITLE
Remap classes

### ISSUE THREAD

**Issue by ebgoldstein** [dbuscombe-usgs/dash_doodler#22]
make a utility to remap classes, akin the the existing workflow in SegZoo. (I would assign myself, but i don't have perms to do that)

**Comment by ddbuscombe** [comment]
- [x] assigned evan as admin
- [ ] add utility
- [ ] add to docs

**Comment by ddbuscombe** [comment]
Is this still needed?

**Comment by ebgoldstein** [comment]
i don't think so, i think it would always be done in Gym and Zoo.. i forget why i thought it would be useful..
If i remember, i will open it and do it
