### ISSUE TITLE
Launching Doodler from website instructions - cairocffi library failure

### ISSUE THREAD

**Issue by jover-usgs** [dbuscombe-usgs/dash_doodler#26]
Just re-cloned doodler onto my laptop and was trying to launch doodler.py using the step by step instructions on the webpage and got the error

![image](https://user-images.githubusercontent.com/61466548/157483899-c539c8fd-f9ea-4727-a3f0-ec307c27c7d7.png)

**Comment by ddbuscombe** [comment]
Hmmm that's a new one.

Can you please

`conda install cairo`

and report back the output you get?

**Comment by ddbuscombe** [comment]
If the above doesnt solve the issue, there are 3 ways to install the conda environment listed on the [github readme](https://github.com/Doodleverse/dash_doodler#%EF%B8%8F-installation), so we could try one of the alternatives

but lmk if a simple `conda install cairo` fixes it?

**Comment by jover-usgs** [comment]
That did not fix it - it updated the cairo package but returned the same error. I'll check out the other installation methods.

**Comment by ddbuscombe** [comment]
I would be tempted to start over

```
conda env remove -n dashdoodler
conda clean --all
conda update conda
conda env create --file environment/dashdoodler-clean.yml
```

**Comment by jover-usgs** [comment]
Reset - same error, reset used the other yml file, same error. Reset, re-cloned, same error. Reset, tried using the conda forge and requirements.txt style - the dashcorecomponents and  scikitimage both throw errors of not existing. 

This is real weird to me - I know I've gotten doodler to work in previous versions!

**Comment by ddbuscombe** [comment]
This is super weird. 

In your activated `dashdoodler` environment, please copy the contents of the output of `conda list` into a text file and post here. I will examine what packages were installed

@2320sharon is this something you have encountered?

**Comment by ddbuscombe** [comment]
Here is my conda list. You can see it installs the following cairo packages

```
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
cairocffi                 1.2.0              pyhd8ed1ab_0    conda-forge
cairosvg                  2.5.2              pyhd8ed1ab_0    conda-forge
```

[doodler-conda-env-dan.txt](https://github.com/Doodleverse/dash_doodler/files/8217068/doodler-conda-env-dan.txt)

**Comment by jover-usgs** [comment]
I have all of those cairo packages at the very least.

[Condalist_jover_dashdoodler.txt](https://github.com/Doodleverse/dash_doodler/files/8217080/Condalist_jover_dashdoodler.txt)

**Comment by ddbuscombe** [comment]
I'm stumped. Let me do some investigating ...

**Comment by jover-usgs** [comment]
I'll see if I can recruit someone else to try and download it to see if I can recreate the error

**Comment by ddbuscombe** [comment]
I just installed an environment using

```
conda create --name dashdoodler python=3.6
conda activate dashdoodler
conda install -c conda-forge pydensecrf cairo cairosvg
conda install -c conda-forge scikit-learn scikit-image psutil dash flask-caching requests
pip install -r environment/requirements.txt
```

I updated the repo with a new (smaller) `environment/requirements.txt` file

please destroy any dashdoodler environments, `git pull` the latest repo, then recreate the environment according to the recipe above

(Note we are stuck with python 3.6 because the `pydensecrf` package needs updating on conda-forge. this is what is causing most conda problems )

**Comment by ddbuscombe** [comment]
@jover-usgs any joy? If not, we may have to contact the `pydensecrf` conda-forge package maintainers to see what can be done about the old python version, which is probably what is causing the problems

**Comment by ddbuscombe** [comment]
@jover-usgs any updates? Nobody else I have spoken with is able to reproduce this error

**Comment by jover-usgs** [comment]
Even I can't reproduce it - I got doodler to work on my workstation, so its just my dumb ol laptop.

**Comment by ddbuscombe** [comment]
Ok. Closing issue but please reopen it if you want to troubleshoot your laptop later
