### ISSUE TITLE
error running utility

### ISSUE THREAD

**Issue by csherwood-usgs** [dbuscombe-usgs/dash_doodler#29]
Got this error when trying to run the utility script.
```
(dashdoodler) C:\crs\src\dash_doodler\utils>gen_images_and_labels.py
Traceback (most recent call last):
  File "C:\crs\src\dash_doodler\utils\gen_images_and_labels.py", line 32, in <module>
    from image_segmentation import *
  File "../app_files/src\image_segmentation.py", line 36, in <module>
    from sklearn.neural_network import MLPClassifier
ImportError: No module named sklearn.neural_network
```

I don't understand what is happening here, because this little test script runs without errors in \dash_doodler\utils:
```
import sys, os, getopt, shutil
sys.path.insert(1, '../app_files/src')
# from annotations_to_segmentations import *
from image_segmentation import *
from sklearn.neural_network import MLPClassifier
print('done')
```
and I can run `image_segmentation.py` on its own without any errors.
My `dashdoodler` environment was built from the .yml file and has scikit-learn 0.24.2
Only addition to the env is m2-base.

What could be going on?

**Comment by ddbuscombe** [comment]
That is bizarre. I have no idea. I am also using scikit-learn 0.24.2 but don't get that error

Can you `import sklearn` or `import sklearn.neural_network as sknn` successfully?

Assuming scikit-learn is at fault, you could try

```
conda update scikit-learn
```

or even a specific version from pip

```
pip install "scikit_learn==0.22"
```

**Comment by ddbuscombe** [comment]
this could be related https://github.com/al-mcintyre/mCaller/issues/29 (although I am using 0.24.2 succesffuly)

Advice seems to be to downgrade

**Comment by csherwood-usgs** [comment]
Oh no. Operator error. Please close this issue and hide it from everyone. I was typing

`gen_images_and_labels.py`

instead of

`python gen_images_and_labels.py`

The error message was not especially helpful, but sheesh.
