### ISSUE TITLE
doodler.py points to nonexistent sample image zip location

### ISSUE THREAD

**Issue by jmdelvecchio** [dbuscombe-usgs/dash_doodler#33]
Clean install of Doodler this morning (06/15) and tried to run `python doodler.py`. Upon execution `doodler.py` tries to download 
`url='https://github.com/dbuscombe-usgs/dash_doodler/releases/download/data/sample_images.zip'`
but throws an error about bad zip file and halts execution. 

Turns out that url doesn't exist and I tried to hunt down an alternative location for the sample images on the repo to no avail. 

Set `DOWNLOAD_SAMPLE` to `False` in `environment/settings.py` and GUI loads up normally.

**Comment by ddbuscombe** [comment]
Thanks for the heads-up! No idea what happened, but will look into it. I should also let you know that some other users have reported issues with doodler that I am looking into. I have started a new experimental fork [here](https://github.com/dbuscombe-usgs/dash_doodler) that I am hoping to use to make improvements to execution speed, and to clean up a lot of redundant code. The basic functionality and outputs won't change

**Comment by ddbuscombe** [comment]
Oh, I see what happened. When I made a new fork, that broke the URL redirects from https://github.com/dbuscombe-usgs/dash_doodler to https://github.com/Doodleverse/dash_doodler.

**Comment by ddbuscombe** [comment]
Latest push should fix this issue
