### ISSUE TITLE
Issues with Zoom

### ISSUE THREAD

**Issue by eol3mk** [dbuscombe-usgs/dash_doodler#34]
When I zoom in, it lets me make one doodle, then it zooms back out to the original zoom settings. It will also zoom back out when switching between the types of tools at the top. It would be great to have the zoom stay put until directing it to zoom back out

**Comment by ddbuscombe** [comment]
Unfortunately, yes, zoom is not working well since the start. My advice has always been "dont use zoom" (I never need it, because I use small image tiles)

but if you need zoom, this guide may help https://doodleverse.github.io/dash_doodler/blog/2021/07/08/Doodler-Zoom
