### ISSUE TITLE
Plotly Library Error in plot_label_generation.py

### ISSUE THREAD

**Issue by venuswku** [dbuscombe-usgs/dash_doodler#39]
I was following [this documentation](https://doodleverse.github.io/dash_doodler/docs/tutorial-basics/what-to-do/#inspect-the-results) for inspecting my labeling results, and I ran into the following error when I tried running `python plot_label_generation.py {-m [0 or 1] -p [0 or 1] -l [0 or 1]}` to get a detailed analysis of my doodles.

@2320sharon mentioned that the import for Plotly Express (`import plotly.express as px`) was removed from `plot_label_generation.py` and the code wasn't adjusted.

### Error Message
```
(dashdoodler) C:\Users\Venuxk\Projects\doodler\utils>python plot_label_generation.py {-m [0 or 1] -p [0 or 1] -l [0 or 1]}
Your session defaults loaded
save mode: 1
threshold intra-label distance: 2
  0%|                                                                                            | 0/2 [00:00<?, ?it/s]Working on C:/Users/Venuxk/Projects/doodler/results/results2022-08-19-11-13\D800_20160308_222129lr02-2_Enter-user-ID.npz
  0%|                                                                                            | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "plot_label_generation.py", line 640, in <module>
    gen_plot_seq(orig_distance, save_mode)
  File "plot_label_generation.py", line 128, in gen_plot_seq
    class_label_colormap = px.colors.qualitative.G10
NameError: name 'px' is not defined
```

### Replicate Issue
- Checkout to this branch: https://github.com/venuswku/doodler/tree/plotly-import-error.
- Create and activate your Anaconda environment by following [these instructions](https://github.com/Doodleverse/dash_doodler#%EF%B8%8F-installation), starting from step 2.
- Run `python plot_label_generation.py {-m [0 or 1] -p [0 or 1] -l [0 or 1]}` in your terminal to see the error. It should try to run an analysis on my results in the `doodler\results\results2022-08-19-11-13` folder.

**Comment by ddbuscombe** [comment]
Thanks for this. Should be fixed by adding `import plotly.express as px` to imports of `plot_label_generation.py`. I'm happy for you to make that change, otherwise I'll get to it when I can (at the moment, I am limited - I cannot use git from my office)

**Comment by ddbuscombe** [comment]
I regained access to using git on my office computer and made this tweak. Pushed straight to main.

**Comment by venuswku** [comment]
Oops, just saw this but glad it's fixed now!
