### ISSUE TITLE
Image Selection Bug

### ISSUE THREAD

**Issue by 2320sharon** [dbuscombe-usgs/dash_doodler#4]
After an image has been segmented sometimes a bug will occur where the image selected will not change to the new one the user has clicked. I have a screenshot below that shows that when I clicked a new image to doodle it did not change the image selected until I clicked it a second time.

![dash-doodler_bug](https://user-images.githubusercontent.com/61564689/174405082-d33e25d2-2805-405c-9f7c-bfa0973f5186.gif)

**Comment by dbuscombe-usgs** [comment]
It is fairly normal to see issues with file selection due to the timer thread. The advice I have given is either a) select and wait for the file name to appear in the box, or b) select twice
