### ISSUE TITLE
issues with Doodler on Chrome + M1 Mac

### ISSUE THREAD

**Issue by ebgoldstein** [dbuscombe-usgs/dash_doodler#40]
A Doodler operator @rtmccune reported issues with Doodler on an M1 mac.. 

you can see the problem here: https://github.com/NCRoadNetworks/PiCamML/issues/8

```
Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```
When i google around, i see this is an M1 issue.. I am not sure it is fixable on our end

**Comment by ebgoldstein** [comment]
I am labeling this with a 'won't fix', but we could change it if someone has ideas...

**Comment by ddbuscombe** [comment]
Not familiar with this issue, or library, or macs, but could it be a simple matter of `pip install cffi`? or `pip install cffi --force-reinstall`?

**Comment by rtmccune** [comment]
Reinstalling cffi seems to be the fix. Doodler is now working!

**Comment by ebgoldstein** [comment]
nice - great to know!
