### ISSUE TITLE
pydensecrf install problems

### ISSUE THREAD

**Issue by ebgoldstein** [dbuscombe-usgs/dash_doodler#45]
see this issue from @FlorisCalkoen in the Gym repository..

https://github.com/Doodleverse/segmentation_gym/issues/102#issuecomment-1296307130 :

> ....the errors mostly refer to the package not being available on the conda channel. I tried to install it in several ways:
> 
> ``` conda create --name dashdoodler python=3.8
> conda install -c conda-forge pydensecrf cairo cairosvg scikit-learn scikit-image psutil dash flask-caching requests pandas matplotlib ipython tqdm  # PackagesNotFoundError: The following packages are not available from current channels:
>   - pydensecrf
> ```
> ``` 
> conda create --name dashdoodler pydensecrf # PackagesNotFoundError: The following packages are not available from current channels:
>   - pydensecrf
> ```
> ``` 
> conda create --name dashdoodler python=3.8
> pip install pydensecrf
> ```

**Comment by ddbuscombe** [comment]
A viable version of this package is only available on conda-forge https://anaconda.org/conda-forge/pydensecrf

Therefore `pip install pydensecrf` will not work

Neither will `conda create --name dashdoodler pydensecrf ` (unless you specify the conda-forge channel)

I would suggest doing some conda cleaning `conda clean --all` and updating conda and anaconda to the latest versions, then trying the `conda install -c conda-forge pydensecrf` (I have installed this conda environment and package a few times this past week on a variety of platforms, so I'm fairly sure this works!)

**Comment by ddbuscombe** [comment]
removed the bug label. this does not appear to be a Doodler bug

**Comment by ddbuscombe** [comment]
i noticed that the package was updated "3 hours and 47 minutes ago" .... not sure if it would be worth another try with this latest version?

**Comment by ebgoldstein** [comment]
Hi @FlorisCalkoen , can you try the above steps outlined by @dbuscombe-usgs and report back? 
For now, i am going to close this issue...

**Comment by FlorisCalkoen** [comment]
My default channel is conda forge, so the issue remains the same.. 

Just check it to be sure, but fails with `  - nothing provides requested pydensecrf`

**Comment by ddbuscombe** [comment]
Please could you

1. `conda clean --all`
2. `conda update -n base conda`
3. `conda update -n base anaconda`
4. create a new conda env just for testing this package, and dont specify a version e.g. `conda create --name test`
5. then `conda activate test`
6. `conda install -c conda-forge pydensecrf`

what output do you get?

**Comment by ebgoldstein** [comment]
ok, just so we are one the same page:
- you tried: `conda install -c conda-forge pydensecrf` (even though conda forge is your default)?
- you did a conda clean and updated to latest version of conda?

**Comment by FlorisCalkoen** [comment]
Thanks for the support guys! Here is my output:
```
~/.conda base ❯ conda create --name test
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/calkoen/miniconda3/envs/test



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Retrieving notices: ...working... done
~/.conda base ❯ conda activate test
~/.conda test ❯ conda install -c conda-forge pydensecrf
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pydensecrf

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


~/.conda test ❯
~/.conda test ❯ conda --version
conda 22.9.0
~/.conda test ❯
```

**Comment by FlorisCalkoen** [comment]
I only have miniconda installed btw, but this shouldn't matter. And I'm on a mac m1. What about you? Are you able to recreate the env?

EDIT: it might actually be a mac issue. Can you confirm you're able to recreate the env and on either linux/windows?

**Comment by ebgoldstein** [comment]
( i have used PoP!_OS 21.10 and various ubuntu versions) 
and yes i just built the env on linux just now
we have tons of experience of doodler working well w/ Linux and windows...

M1 has had some weirdness w/ doodler (i.e., https://github.com/Doodleverse/dash_doodler/issues/40) ...... 
...(i'm asking an M1 user about this right now...)

**Comment by ddbuscombe** [comment]
I would help troubleshoot, but now I have run into SSL errors which means I cant use conda at all :(

**Comment by FlorisCalkoen** [comment]
So I just checked on linux instance and I'm able to install the package without problems (see output below). So it should be a mac m1 issue..  

```
echo $OSTYPE  # linux-gnu
cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
...
```

Possible workaround is of course to use a conda installation managed by rosetta. However, the preferred workflow would be that the package managers of pydensecrf publish their package as well on the osx-arm64 conda channel. This is the first package I encounter in months that is not available over there.

**Comment by ddbuscombe** [comment]
pydensecrf continues to be a big problem. We tried for a long time to get the package maintainers to merge our PR or update it .... see (spaces removed to avoid directly linking)

https://github.com/ lucasb-eyer/ pydensecrf/ issues/ 114

**Comment by ddbuscombe** [comment]
Does reverting back to python 3.7 help?

**Comment by FlorisCalkoen** [comment]
Nope, I think it's really the package not being available on the osx-arm64 channel. Where do you use pydensecrf for?

**Comment by ddbuscombe** [comment]
Ok, thanks for the info. We conclude that, at least for now, `osx-arm64` is not supported. Sorry - this is because the original package repo is no longer maintained. `pydensecrf` is a major dependency - it is the main ML that Doodler is based upon. We will have to go back to the drawing board if we want to continue to use `pydensecrf`

You won't need it to unpack the Coast Train data, though, so just build the conda env without it

**Comment by FlorisCalkoen** [comment]
Ok, fair point. But where do you use that package for? Maybe something else can be used :)? Or is it critical infrastructure?

Regarding your last point, I don't think I'll (or any mac m1 users) will be able to use the doodler now. At least not to load the training data. Running that script `gen_images_and_labels.py` requires doodler_engine which requires pydensecrf (see output below).

When I have some processing steps  to load the training data I'll share them at [that other issue](https://github.com/Doodleverse/segmentation_gym/issues/102#issuecomment-1296307130).

``` bash
❯ conda list
# packages in environment at /Users/calkoen/miniconda3/envs/dashdoodler:
#
# Name                    Version                   Build  Channel
aom                       3.5.0                h7ea286d_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               hd414afc_3    conda-forge
brotli                    1.0.9                h1a8c8d9_8    conda-forge
brotli-bin                1.0.9                h1a8c8d9_8    conda-forge
brotli-python             1.0.9            py38h2b1e499_8    conda-forge
brotlipy                  0.7.0           py38hb991d35_1005    conda-forge
brunsli                   0.1                  h9f76cd9_0    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
c-blosc2                  2.4.3                h303ed30_0    conda-forge
ca-certificates           2022.9.24            h4653dfc_0    conda-forge
cachelib                  0.9.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            h73a0509_1014    conda-forge
cairocffi                 1.3.0              pyhd8ed1ab_0    conda-forge
cairosvg                  2.5.2              pyhd8ed1ab_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38ha45ccd6_2    conda-forge
cfitsio                   4.1.0                hd4f5c17_0    conda-forge
charls                    2.3.4                hbdafb3b_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.6            py38h9dc3d6a_0    conda-forge
cryptography              38.0.2           py38h23f6d3d_2    conda-forge
cssselect2                0.2.1              pyh9f0ad1d_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0           py38hb991d35_1    conda-forge
dash                      2.6.2              pyhd8ed1ab_0    conda-forge
dask-core                 2022.10.0          pyhd8ed1ab_2    conda-forge
dav1d                     1.0.0                he4db4b2_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
doodler-engine            0.0.3                    pypi_0    pypi
executing                 1.1.1              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hb7217d7_0    conda-forge
flask                     2.2.2              pyhd8ed1ab_0    conda-forge
flask-caching             2.0.1              pyhd8ed1ab_0    conda-forge
flask-compress            1.13               pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.1               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0           py38hb991d35_1    conda-forge
freetype                  2.12.1               hd633e50_0    conda-forge
fsspec                    2022.10.0          pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
giflib                    5.2.1                h27ca646_2    conda-forge
icu                       70.1                 h6b3803e_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2022.9.26        py38h4fe6f40_3    conda-forge
imageio                   2.22.0             pyhfa7a67d_0    conda-forge
importlib-metadata        5.0.0              pyha770c72_1    conda-forge
ipython                   8.6.0              pyhd1c38e8_1    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   he4db4b2_2    conda-forge
jxrlib                    1.1                  h27ca646_2    conda-forge
kiwisolver                1.4.4            py38h9dc3d6a_1    conda-forge
krb5                      1.19.3               he492e65_0    conda-forge
lcms2                     2.13.1               h8193b64_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libaec                    1.0.6                hbdafb3b_0    conda-forge
libavif                   0.11.1               h3d80962_0    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_8    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_8    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_8    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libcurl                   7.86.0               h1c293e1_0    conda-forge
libcxx                    14.0.6               h2692d47_0    conda-forge
libdeflate                1.14                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           11_3_0_hd922786_25    conda-forge
libgfortran5              11.3.0              hdaf2cc0_25    conda-forge
libglib                   2.74.1               h14ed1c1_0    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libnghttp2                1.47.0               h519802c_1    conda-forge
libopenblas               0.3.21          openmp_hc731615_3    conda-forge
libpng                    1.6.38               h76d750c_0    conda-forge
libsqlite                 3.39.4               h76d750c_0    conda-forge
libssh2                   1.10.0               h7a5bd25_3    conda-forge
libtiff                   4.4.0                hfa0b094_4    conda-forge
libwebp-base              1.2.4                h57fd34a_0    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
libzopfli                 1.0.3                h9f76cd9_0    conda-forge
llvm-openmp               14.0.4               hd125106_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
markupsafe                2.1.1            py38hb991d35_2    conda-forge
matplotlib                3.6.1            py38h150bfb4_1    conda-forge
matplotlib-base           3.6.1            py38hbbe890c_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
networkx                  2.8.7              pyhd8ed1ab_0    conda-forge
numpy                     1.23.4           py38h09ac2d9_1    conda-forge
openjpeg                  2.5.0                h5d4e404_1    conda-forge
openssl                   3.0.5                h03a7124_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.5.1            py38h61dac83_1    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pcre2                     10.37                hcf5f1cc_1    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py38hf86a106_3    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
plotly                    5.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
psutil                    5.9.3            py38hb991d35_1    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.13          hd3575e6_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.5             pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py38hb39dbe9_2    conda-forge
pyyaml                    6.0              py38hb991d35_5    conda-forge
readline                  8.1.2                h46ed386_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
scikit-image              0.19.3           py38h61dac83_2    conda-forge
scikit-learn              1.1.3            py38h0c332d6_1    conda-forge
scipy                     1.9.3            py38h7b4f323_1    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h39c3846_1    conda-forge
sqlite                    3.39.4               h2229b38_0    conda-forge
stack_data                0.5.1              pyhd8ed1ab_0    conda-forge
tenacity                  8.1.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2022.10.10         pyhd8ed1ab_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py38hb991d35_1    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.5.0              pyhd8ed1ab_0    conda-forge
unicodedata2              15.0.0           py38hb991d35_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
versioneer                0.28                     pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.2.2              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zfp                       1.0.0                hb6e4faa_3    conda-forge
zipp                      3.10.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h03a7124_4    conda-forge
zlib-ng                   2.0.6                he4db4b2_0    conda-forge
zstd                      1.5.2                h8128057_4    conda-forge
❯ python utils/gen_images_and_labels.py
Traceback (most recent call last):
  File "utils/gen_images_and_labels.py", line 33, in <module>
    from doodler_engine.annotations_to_segmentations import *
  File "/Users/calkoen/miniconda3/envs/dashdoodler/lib/python3.8/site-packages/doodler_engine/annotations_to_segmentations.py", line 37, in <module>
    from .image_segmentation import segmentation
  File "/Users/calkoen/miniconda3/envs/dashdoodler/lib/python3.8/site-packages/doodler_engine/image_segmentation.py", line 41, in <module>
    import pydensecrf.densecrf as dcrf
ModuleNotFoundError: No module named 'pydensecrf'
```

**Comment by ebgoldstein** [comment]
OK, to summarize:

M1 mac users will not be able to use doodler (or utils). This will impact their ability to create training data via doodler (obviously) and also use the handy `util` scripts to reconstitute CoastTrain. This is an issue for sure, but not one we have time for right now here at Doodleverse HQ.. Everytime we have run into an M1 issue, an operator is able to just pivot to use another machine with a different OS, so no one  has reported being fully stopped by the M1 issue. So it is in the list of things that need fixing, but not the highest thing on the list.

- @FlorisCalkoen - `pydensecrf` is currently 'critical infrastructure' for the code. There is no drop-in replacement that we know of. So we will not be removing this dependency until we have some time on our hands.  If we had a replacement (or if we removed it completely) we would need a refactor and - more importantly - we would want to do *lots* of testing to understand if any code changes resulting in changed functionality. If you can find a drop in replacement, feel free to mention it to us (you can look in doodleverse_engine to see the functions we need)... Also feel free to fork that code and experiment if you have other solutions/ideas/replacements in mind. we are always happy to test out new code contributions!


- @FlorisCalkoen , this all started because you wanted the CoastTrain labels, right? I just skimming over [`gen_images_and_labels`](https://github.com/Doodleverse/dash_doodler/blob/main/utils/gen_images_and_labels.py), and it does not rely on pydensecrf. So it seems straightforward to make this a 'stand-alone' function that could be used by anyone to reconsittute the CoastTrain labels without needing to write their own code. With that in mind, i see four options, and i put them in rank order:
1) you use a linux or windows machine to use the doodler workflow that we have recommended from the beginning. It seems you have access to one of these machines?
2) You contribute to this project by writing some code to make the exact labels you need, and adding the code via a PR to the repository (i think the CoastTrain repository would be best..
3) You tell me what labels you want, and i put them in a dropbox/googledrive for you after using the doodler workflow
4) You wait for us to write a stand-alone snippet of code that makes labels from the CoastTrain data, (that does not rely on installing doodler_engine), which we will probably put on the CoastTrain github repo. We will likely do this eventually, but it is behind a bunch of other tasks.

**Comment by ddbuscombe** [comment]
Excellent summary thanks @ebgoldstein

**Comment by FlorisCalkoen** [comment]
@ebgoldstein, thanks for the summary! 

I fully understand you don't have the priority to fix this issue for the odd mac m1 user, especially since those users are often capable of finding an easy workaround themselve. The intention of opening this issue was only to keep you posted about (dependency) constraints of your workflow and/or collaboratively improve the accessibility of your dataset. 

Regarding some of your points:
1. Yes, I do have access to both window/linux, but for my own workflow it's nice if things just work on all OS. Also - correct me if I'm wrong - Doodler is mostly a GUI application, or is at least built with being a GUI in mind. The linux instances I have access to typically don't have xservers installed, so running GUI's is not that straightforward. 
2. Preferred option.  I'll share my snippets or create PR when I'm done (not sure if I'll be able to find the time this week). Do you have a link to the coastrain repository? Tbh all different Doodleverse / Segmentation Gym repositories can be a bit confusing to a new user.
