### ISSUE TITLE
the longstanding "Doodles persist" issue - is it browser-dependent?

### ISSUE THREAD

**Issue by ddbuscombe** [dbuscombe-usgs/dash_doodler#48]
Doodler uses a timer to periodically search through the `assets` and `labeled` folders, reconcile them, and update the image list. This is to ensure that you dont doodle the same image twice

The code that does that is https://github.com/Doodleverse/dash_doodler/blob/main/app.py#L482

(this is why you often have to select images a few times before they 'stick')

That is also supposed to clear the doodles from the main window. Often, it does not; doodles 'persist' from the previous image. The only known workaround is a browser refresh, which is annoying (-ly slow)

Changing `interval=500` to a higher number, say `interval=1000`, or a lower number, say `interval=100`, did not help

Switching browsers, from Chrome to Firefox, helped a LOT. Hey The 4 MuskaDoodlers! @venuswku @ebgoldstein @2320sharon @CameronBodine - you seeing the same thing? Which browser do you use? have you noticed big differences between them?

**Comment by ebgoldstein** [comment]
I use firefox. file selection is rarely a problem. I typically wait ~2 seconds after selecting an image before i slip over to the doodling interface. 

(is the same selection issue as #12 ?)

**Comment by 2320sharon** [comment]
I typically use Google Chrome when I'm doodling. I recall having the persisting doodles error occur occasionally, but I have encountered it since the latest update to doodler. That being said I also haven't been doodling much.

**Comment by 2320sharon** [comment]
![doodler_file_selection_bug_chrome_gif](https://user-images.githubusercontent.com/61564689/199579181-e0920427-bf72-466d-8879-24aaaeb06e61.gif)
Also @dbuscombe-usgs not sure if you're aware of this quirk in doodler, but on Google Chrome when the user initially loads up doodler none of the files are shown. They have to switch back to the main page of doodler and then click the file tab again for the files to appear. This has happened every single time I have opened doodler with Google Chrome.

**Comment by ddbuscombe** [comment]
Thanks @2320sharon that's good input. I noticed only yesterday how bad Chrome was w/r/t the 'persistent doodle' problem. It almost went away switching to Firefox. It seems like everyone has a slightly different experience ... it would be nice to understand what exactly happens when those doodles persist. I don't know enough about browsers and caching to really make headway. But thanks for the info!!

**Comment by 2320sharon** [comment]
Happy to help! For now, it might be a good idea to recommend that users use FireFox. Digging into browser-specific issues can be a pain and sometimes result from the package you're using to compile python code to javascript rather than your code.
