### ISSUE TITLE
dash_doodler website not accessible

### ISSUE THREAD

**Issue by liten82** [dbuscombe-usgs/dash_doodler#58]
Hello, trying to access the website 
[https://dbuscombe-usgs.github.io/dash_doodler/](url)
which gives a '404 file not found' message. To my understanding, this address leads to the newest version of the Doodler labelling tool. Is this a technical issue or is the address just no longer up to date?
Thanks a lot!
Efi

**Comment by ebgoldstein** [comment]
Hi @liten82 - I'll let @dbuscombe-usgs respond more fully (I imagine that 404 might just be a result of 'link rot'), but this is the repository for Dash Doodler.. 
You can look on the Readme to check out the [install instructions](https://github.com/Doodleverse/dash_doodler?tab=readme-ov-file#%EF%B8%8F-installation)

does this answer your question?

**Comment by liten82** [comment]
Hi @ebgoldstein  and thanks for the swift reply.
I just managed to acces a Doodler website [https://doodleverse.github.io/dash_doodler/](url)
by clicking the the link  under _Doodler website_  in section _Unpacking NPZ files_ ,in webpage [https://coasttrain.github.io/CoastTrain/docs/Version%201:%20March%202022/data/](url) 
The Doodler website address that works is different from what I tried inititally -in my first post- so I suppose it was outdated.
The issue seems to be fixed now, thank you!
